export const ColumnsActionTypes = {
  FETCH_COLUMNS_START: "FETCH_COLUMNS_START",
  FETCH_COLUMNS_SUCCESS: "FETCH_COLUMNS_SUCCESS",
  FETCH_COLUMNS_FAILURE: "FETCH_COLUMNS_FAILURE",

  CLEAR_COLUMNS: "CLEAR_COLUMNS",

  CREATE_COLUMN_START: "CREATE_COLUMN_START",
  CREATE_COLUMN_SUCCESS: "CREATE_COLUMN_SUCCESS",
  CREATE_COLUMN_FAILURE: "CREATE_COLUMN_FAILURE",

  UPDATE_COLUMN_START: "UPDATE_COLUMN_START",
  UPDATE_COLUMN_SUCCESS: "UPDATE_COLUMN_SUCCESS",
  UPDATE_COLUMN_FAILURE: "UPDATE_COLUMN_FAILURE",

  DELETE_COLUMN_START: "DELETE_COLUMN_START",
  DELETE_COLUMN_SUCCESS: "DELETE_COLUMN_SUCCESS",
  DELETE_COLUMN_FAILURE: "DELETE_COLUMN_FAILURE",
}

export default ColumnsActionTypes
