export const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",

  UPDATE_CURRENT_USER_START: "UPDATE_CURRENT_USER_START",
  UPDATE_CURRENT_USER_SUCCESS: "UPDATE_CURRENT_USER_SUCCESS",
  UPDATE_CURRENT_USER_FAILURE: "UPDATE_CURRENT_USER_FAILURE",
}
