export const EntriesActionTypes = {
  FETCH_ENTRIES_START: "FETCH_ENTRIES_START",
  FETCH_ENTRIES_SUCCESS: "FETCH_ENTRIES_SUCCESS",
  FETCH_ENTRIES_FAILURE: "FETCH_ENTRIES_FAILURE",

  CLEAR_ENTRIES: "CLEAR_ENTRIES",

  CREATE_ENTRY_START: "CREATE_ENTRY_START",
  CREATE_ENTRY_SUCCESS: "CREATE_ENTRY_SUCCESS",
  CREATE_ENTRY_FAILURE: "CREATE_ENTRY_FAILURE",

  UPDATE_ENTRY_START: "UPDATE_ENTRY_START",
  UPDATE_ENTRY_SUCCESS: "UPDATE_ENTRY_SUCCESS",
  UPDATE_ENTRY_FAILURE: "UPDATE_ENTRY_FAILURE",

  DELETE_ENTRY_START: "DELETE_ENTRY_START",
  DELETE_ENTRY_SUCCESS: "DELETE_ENTRY_SUCCESS",
  DELETE_ENTRY_FAILURE: "DELETE_ENTRY_FAILURE",
}

export default EntriesActionTypes
