export const EntriesActionTypes = {
  FETCH_ENTRIES_START: "FETCH_ENTRIES_START",
  FETCH_ENTRIES_SUCCESS: "FETCH_ENTRIES_SUCCESS",
  FETCH_ENTRIES_FAILURE: "FETCH_ENTRIES_FAILURE",
  CLEAR_ENTRIES: "CLEAR_ENTRIES",
}

export default EntriesActionTypes
